### ISSUE TITLE
empty context.getUser() when made a request from react. (it works in playground)

### ISSUE THREAD

**Issue by josuevalrob** [ericbf/graphql-passport#46]
Hello. 

I am trying to login and update a collection. 

This is my context creation: 
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req, res }) => {
    return buildContext({ req, res, User })
  },
  playground: {
    settings: {
      'request.credentials': 'same-origin',
    },
  },
});
```
I have [here](https://github.com/josuevalrob/cle_api/blob/4a49ec411c117bc814395c5ffb54ceaba5713daa/src/resolvers/users/user.mutations.js#L42) a console log who perfectly made the validation and can log out the current user in the context: 
`    console.log('💃 ', context.req.user) `

Later on, in my [secure middleware ](https://github.com/josuevalrob/cle_api/blob/4a49ec411c117bc814395c5ffb54ceaba5713daa/src/middlewares/secure.mid.js#L43)  i am hable to get the context for future request: 
```
		if (!context.getUser()) 		 throw new AuthenticationError('Unauthenticated')
		const {id, rol} = context.getUser();
```

Now, my problem is when I try to do all this from my [react app ](https://github.com/josuevalrob/CLE), because all this works fine from the playground. 

Because now, the context is complete lost, and i am not able to pass my secure middleware. 

where is my issue? in my react or express app??

**Comment by gforge** [comment]
This is most likely an issue due to the credentials not being sent from the react app. Try changing https://github.com/josuevalrob/CLE/blob/master/src/services/apolloClient.js#L23 to "include"

**Comment by ericbf** [comment]
Marking this as closed—for it to pass the credentials, you should use the appropriate [credentials policy](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/#credentials). Other libraries have similar settings, such as `fetchOptions` under `graphql-hooks`, if you are using that.

If you are running your app locally, you probably want to use the `"include"` credentials policy.
